- name: Ensure yum.repo file exist or not
  stat: 
    path: /etc/yum.repos.d/gocd.repo
  register: yumrepo
- name: Download yum.repo
  get_url:
    url: https://download.gocd.org/gocd.repo
    dest: /etc/yum.repos.d/gocd.repo
    mode: 0644
  when: not yumrepo.stat.exists
- name: Install Openjdk-1.8
  yum:
    name: java-1.8.0-openjdk
    state: present
- name: Create directory /var/go
  file:
    path: /var/go
    state: directory
    mode: 0755
- name: Install go-agent
  command: >
    yum install -y go-agent
- name: "Start go-agent"
  service:
    name: go-agent
    state: started
    enabled: yes